name: clientf
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2


  ## 게시판 목록 캐시에 필요
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

  ## Engine 과 통신하는데 필요
  cloud_functions: ^0.4.2+3

  ## 클라이언트에서 `Firebase Auth`로 로그인을 하는데 필요
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.6

  ## `Firebase Firestore` 에 파일 업로드를 위한 패키지
  firebase_core: ^0.4.4+3
  firebase_storage: ^3.1.5


  ## 컴포넌트를 Android 와 iOS 에 맞춰 다르게 보여주는 위젯.
  flutter_platform_widgets: ^0.32.5


  ## 언어화 위젯
  flutter_localizations:
    sdk: flutter


  ## NetworkImageWithRetry. 사진 URL 이 없는 경우 에러 방지.
  # flutter_image: ^3.0.0

  ## 이미지 캐시 및 URL 오류 방지
  cached_network_image: ^2.2.0+1

  ## App State Management
  provider: ^4.0.1

  ## 사진을 찍거나 갤러리에서 가져온다.
  image_picker: ^0.6.6+1

  ## 사진을 찍거나 갤러리에서 가져와서 사진의 크기를 작게한다.
  flutter_image_compress: ^0.6.7


  ## iOS 에서 사진을 찍을 권한을 물어본다.
  permission_handler: ^5.0.0+hotfix.6


  ## Human readable time
  time_formatter: ^1.0.0


  ## 날짜(생일) 선택
  flutter_datetime_picker: ^1.3.8

  ## Firestore 에 직접 연결
  cloud_firestore: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:    
    - lib/flutter_engine/assets/images/user-icon.png
