name: clientf
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  provider: ^4.0.1
  flutter_platform_widgets: ^0.50.0

  cloud_functions: ^0.4.2+3
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.6

  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

  flutter_localizations:
    sdk: flutter

  firebase_core: ^0.4.4+3
  firebase_storage: ^3.1.5

  image_picker: ^0.6.6+1
  permission_handler: ^5.0.0+hotfix.6
  flutter_image_compress: ^0.6.7

  # NetworkImageWithRetry
  flutter_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:    
    - lib/flutter_engine/assets/images/user-icon.png
